spring:
  application:
    name: ingress-product
  datasource:
    url: jdbc:postgresql://localhost:4444/product_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false


